### ISSUE TITLE
Backend-ish/Decision: Google Cloud Hosting

### ISSUE THREAD

**Issue by LodenH16** [Multiplied-By-One/MBO-App#18]
Look into Google Cloud hosting.

**Comment by ryanolee** [comment]
Is this for data hosting @LodenH16 ?

**Comment by ryanolee** [comment]
Firebase [vendor locks](https://medium.com/@petrhavlicek/be-aware-of-hidden-vendor-lock-d836c8d37c06) us to GCP in either case. So without significant platform changes we would not be able to use another cloud.
