### ISSUE TITLE
Pages: HeadMates Listing Page

### ISSUE THREAD

**Issue by LodenH16** [Multiplied-By-One/MBO-App#8]
This issue is required to complete #7 for the System Map

> *this is taken from the grand pdf [page 41](https://drive.google.com/file/d/1JGqPSo2Lem2A_XrcSU9h19yzHA19k7Ba/view?usp=sharing)*

The System Map profile that is accessed after the basic profile input has additional traits and information that can then be added.

The basic name, gender, age, and profile pic are added, then that appears on the System Map as a clickable button that leads to the associated profile

![image](https://user-images.githubusercontent.com/68450309/191645613-fb1782f1-8e40-4273-9a10-415390d2ea35.png)

**Comment by wendyyng** [comment]
@ryanolee  I've never contributed before, but I think I can help with the frontend for this! I tried to create the system map page and profile cards with mock data:
![screencapture-localhost-3000-system-map-2022-11-04-23_26_11](https://user-images.githubusercontent.com/71687298/200106145-e7767d42-cf20-4b82-9fac-d1e5fda22566.png)

**Comment by ryanolee** [comment]
That looks awesome @wendyyng ! Sorry for being slow to respond on this one. It got buried under the standard github spam. This looks really good! Would you be ok opening a pull request for this on this repository from the fork you were doing the work on 👀

I can try to help you hook everything up if you want. Let me know if you want a quick call on the Multiplied by One Dev Discord to run through it all!

**Comment by wendyyng** [comment]
@ryanolee Sorry for the delay! I just created the PR for the issue! I am unsure of a few things - which you can find in the PR #30 . If you could take a look that would be great! :)
